### PR TITLE
no login page if loggedin

### PR DESCRIPTION
**Pull request by dev-sankhadip**
#23 
Issue resolved and i have created a reusable module which can be used in other pages also.

### CODE REVIEW

**Comment by thebishaldeb** [comment]
You can see that after you press back, you get a glimpse of that page before returning to login page. Also it shows error in the chrome console that blogs of id underfined something. 
We do not want that. Make it such that it directly redirects to the login page. Not on `ComponentDidMount` because that basically loads that component (page) and then does the checking. We do not want that.

**Comment by thebishaldeb** [comment]
I did not nean this. I said do it in such a way that it doesn't even get inside that component if not logged in. Anyway can't use unfase components in fute versions. 

Write some functions such that if checks and then returns route of that component based on the condition, else return login route. It should not enter that route, check and then redirect, rather redirect if it is not authenticated, like it is in keep_clone

**Comment by dev-sankhadip** [comment]
ok got it

**Comment by dev-sankhadip** [comment]
I think this time it has been implemented in right way

**Pull request merged**
