### PR TITLE
project moved to react+graphql

### PR DESCRIPTION
**Pull request by dev-sankhadip**
#1 
Project has been moved to react+graphql stack

### CODE REVIEW

**Comment by thebishaldeb** [comment]
Great Job dude. Just put some screenshots of all the pages so that I can see how it is working. Also describe what you have done in the description.  
I'll then merge it.

**Comment by dev-sankhadip** [comment]
Bro, for now i have just added simple signup page for storing users. Later i will do rest of the pages.

**Comment by thebishaldeb** [comment]
Okay merging it.

**Comment by dev-sankhadip** [comment]
Screenshot from 2019-12-08 19-35-56

**Comment by dev-sankhadip** [comment]
Screenshot from 2019-12-08 19-37-14

**Comment by dev-sankhadip** [comment]
Screenshot from 2019-12-08 19-38-50

**Comment by dev-sankhadip** [comment]
Can i use semantic-ui-react for designing rest of the pages?

**Pull request merged**
