### PR TITLE
Authform implemented

### LINKED ISSUE #2: Add user authentication
After #1 is done, add user authentication so that each user can log in and see his info inside the `New` folder.

Follow the tutorial - https://www.youtube.com/watch?v=7giZGFDGnkc&list=PL55RiY5tL51rG1x02Yyj93iypUuHYXcB_&index=1

No need to care about designing the page.

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
Resolves #2 
- created the backend for auth form
- created the frontend for auth form
- React router is used to view Homepage when sign in is done

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@thebishaldeb pls review and let me know for changes
I have also included a working GIF
ReactApp-GoogleChrome2019-12-090

**Comment by thebishaldeb** [comment]
@ankingcodes Seems like you have included the node_modules. We do not want that in the repo. Also where is the feature of logout? A logout button is needed in homepage if the user is logged in.

**Comment by ankushbhardwxj** [comment]
@thebishaldeb Its only the `jwtwebtoken` package that is necessary for the login and logout. 
Sorry, i missed that `logout` button. Will be adding in another commit 👍

**Comment by thebishaldeb** [comment]
Yeah but can't that be added in the package.json and downloaded in repos using yarn or non install. I guess save it in package.json and use it rather than including the node nodules would be a better option.

**Comment by ankushbhardwxj** [comment]
Certainly, will do that too

**Comment by ankushbhardwxj** [comment]
@thebishaldeb I added the logout button but I have  a difficulty with the node_modules. How to I get rid of them ? I did run a command `npm uninstall jwtwebtoken --save` .Is that enough?

**Pull request closed without merging**
